### ISSUE TITLE
调用退款报错：Pass phrase must be a buffer

### ISSUE THREAD

**Issue by wulisensen** [wbget/egg-wxpay#3]
node: 10
npm: 6.9.0

```js
config.wxpay = {
        appId: '4242',
        appSecret: '4242342',
        // 微信商户
        mchId: 424234,
        apiKey: '23424242',
        notifyUrl: 'http://test.com/notifyUrl',
        body: '测试',
        partnerKey: '111111111', // 商户密钥
        ca: fs.readFileSync('./app/cert/apiclient_cert.pem'),
        pfx: fs.readFileSync('./app/cert/apiclient_cert.p12'),
    };
```

**Comment by wulisensen** [comment]
nodejs.TypeError: Pass phrase must be a buffer
    at Object.createSecureContext (_tls_common.js:210:19)
    at Object.connect (_tls_wrap.js:1127:48)
    at Agent.createConnection (https.js:120:22)
    at Agent.createSocket (_http_agent.js:227:26)
    at Agent.addRequest (_http_agent.js:185:10)
    at new ClientRequest (_http_client.js:249:16)
    at Object.request (https.js:289:10)
    at Payment._httpsRequest (/Users/wuguangsen/ifeng/work/lego-system/node_modules/wechat-pay/lib/payment.js:179:19)
    at Payment._signedQuery (/Users/wuguangsen/ifeng/work/lego-system/node_modules/wechat-pay/lib/payment.js:255:3)
    at Payment.refund (/Users/wuguangsen/ifeng/work/lego-system/node_modules/wechat-pay/lib/payment.js:288:8)
    at Promise (/Users/wuguangsen/ifeng/work/lego-system/node_modules/wechat-pay/lib/payment.js:494:16)
    at new Promise (<anonymous>)
    at Payment.(anonymous function) [as refund] (/Users/wuguangsen/ifeng/work/lego-system/node_modules/wechat-pay/lib/payment.js:478:16)
    at WechatService.refund (/Users/wuguangsen/ifeng/work/lego-system/app/service/wechat.js:224:46)
    at OrderController.refund (/Users/wuguangsen/ifeng/work/lego-system/app/controller/order.js:564:53)
    at process._tickCallback (internal/process/next_tick.js:68:7)
code: "ERR_INVALID_ARG_TYPE"
pid: 12012

**Comment by wbget** [comment]
看起来像是调用传参类型不对，可能你得自己试下。
我已经去用[egg-tenpay](https://github.com/wbget/egg-tenpay)了，这个就没管了。

**Comment by wulisensen** [comment]
大哥，egg-tenpay支持退款不

**Comment by wbget** [comment]
> 大哥，egg-tenpay支持退款不

有啊，应该是可以直接用的，你看他的API，参考着支付写。

**Comment by wulisensen** [comment]
> > 大哥，egg-tenpay支持退款不
> 
> 有啊，应该是可以直接用的，你看他的API，参考着支付写。

是我传参错了，mchid传了个数值型进去
